dock_config_waypoint:  # Navigated to when wall detection times out or is disabled.
  mode: only_position
  position:
    x: 0.0
    y: 7.5
    z: 1.0
  orientation:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  convergence_threshold: 0.3
