fallback_docking_waypoint:  # Navigated to when service_request_state times out during search.
  mode: 0
  position:
    x: 0.0
    y: 7.5
    z: 1.0
  orientation:
    roll: 0.0
    pitch: 0.0
    yaw: 90.0
  convergence_threshold: 0.3
