/**:
  ros__parameters:
    topics:
      bearing_measurement: bearing_measurement # Single bearing input
      bearing_array: /aruco_detector/marker_directions # Array bearing input
      bearing_localization_markers: bearing_localization/markers # Debug markers
