# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vortex/cv_ws/src/Vortex_CV/camera_calibration/scripts

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vortex/cv_ws/src/Vortex_CV/camera_calibration/scripts

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vortex/cv_ws/src/Vortex_CV/camera_calibration/scripts/CMakeFiles /home/vortex/cv_ws/src/Vortex_CV/camera_calibration/scripts//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vortex/cv_ws/src/Vortex_CV/camera_calibration/scripts/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pls_pls

# Build rule for target.
pls_pls: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pls_pls
.PHONY : pls_pls

# fast build rule for target.
pls_pls/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pls_pls.dir/build.make CMakeFiles/pls_pls.dir/build
.PHONY : pls_pls/fast

#=============================================================================
# Target rules for targets named pls_pls_pls

# Build rule for target.
pls_pls_pls: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pls_pls_pls
.PHONY : pls_pls_pls

# fast build rule for target.
pls_pls_pls/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pls_pls_pls.dir/build.make CMakeFiles/pls_pls_pls.dir/build
.PHONY : pls_pls_pls/fast

#=============================================================================
# Target rules for targets named stereo_calib2

# Build rule for target.
stereo_calib2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stereo_calib2
.PHONY : stereo_calib2

# fast build rule for target.
stereo_calib2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stereo_calib2.dir/build.make CMakeFiles/stereo_calib2.dir/build
.PHONY : stereo_calib2/fast

camera_acquisition.o: camera_acquisition.cpp.o
.PHONY : camera_acquisition.o

# target to build an object file
camera_acquisition.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pls_pls_pls.dir/build.make CMakeFiles/pls_pls_pls.dir/camera_acquisition.cpp.o
.PHONY : camera_acquisition.cpp.o

camera_acquisition.i: camera_acquisition.cpp.i
.PHONY : camera_acquisition.i

# target to preprocess a source file
camera_acquisition.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pls_pls_pls.dir/build.make CMakeFiles/pls_pls_pls.dir/camera_acquisition.cpp.i
.PHONY : camera_acquisition.cpp.i

camera_acquisition.s: camera_acquisition.cpp.s
.PHONY : camera_acquisition.s

# target to generate assembly for a file
camera_acquisition.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pls_pls_pls.dir/build.make CMakeFiles/pls_pls_pls.dir/camera_acquisition.cpp.s
.PHONY : camera_acquisition.cpp.s

stereo_calib.o: stereo_calib.cpp.o
.PHONY : stereo_calib.o

# target to build an object file
stereo_calib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pls_pls.dir/build.make CMakeFiles/pls_pls.dir/stereo_calib.cpp.o
.PHONY : stereo_calib.cpp.o

stereo_calib.i: stereo_calib.cpp.i
.PHONY : stereo_calib.i

# target to preprocess a source file
stereo_calib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pls_pls.dir/build.make CMakeFiles/pls_pls.dir/stereo_calib.cpp.i
.PHONY : stereo_calib.cpp.i

stereo_calib.s: stereo_calib.cpp.s
.PHONY : stereo_calib.s

# target to generate assembly for a file
stereo_calib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pls_pls.dir/build.make CMakeFiles/pls_pls.dir/stereo_calib.cpp.s
.PHONY : stereo_calib.cpp.s

stereo_calib2.o: stereo_calib2.cpp.o
.PHONY : stereo_calib2.o

# target to build an object file
stereo_calib2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stereo_calib2.dir/build.make CMakeFiles/stereo_calib2.dir/stereo_calib2.cpp.o
.PHONY : stereo_calib2.cpp.o

stereo_calib2.i: stereo_calib2.cpp.i
.PHONY : stereo_calib2.i

# target to preprocess a source file
stereo_calib2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stereo_calib2.dir/build.make CMakeFiles/stereo_calib2.dir/stereo_calib2.cpp.i
.PHONY : stereo_calib2.cpp.i

stereo_calib2.s: stereo_calib2.cpp.s
.PHONY : stereo_calib2.s

# target to generate assembly for a file
stereo_calib2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stereo_calib2.dir/build.make CMakeFiles/stereo_calib2.dir/stereo_calib2.cpp.s
.PHONY : stereo_calib2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... pls_pls"
	@echo "... pls_pls_pls"
	@echo "... stereo_calib2"
	@echo "... camera_acquisition.o"
	@echo "... camera_acquisition.i"
	@echo "... camera_acquisition.s"
	@echo "... stereo_calib.o"
	@echo "... stereo_calib.i"
	@echo "... stereo_calib.s"
	@echo "... stereo_calib2.o"
	@echo "... stereo_calib2.i"
	@echo "... stereo_calib2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

