/**:
  ros__parameters:
    # Topics
    detection_sub_topic: "/yolo/detections"
    camera_info_sub_topic: "/nautilus/front_camera/camera_info"
    landmarks_pub_topic: "nautilus/landmarks"

    # Frames
    odom_frame: "odom"

    # How far ahead of the camera to place the waypoint [m]
    waypoint_distance: 2.0
