version: '3.8'
services:

  cv:
    container_name: cv
    
    image: ghcr.io/vortexntnu/vortex-cv:main
    stdin_open: true    #Enable terminal input
    tty: true           #Keep container from closing
    network_mode: host  #Maps ports in container to same port number on computer

  cv-dev:
    container_name: cv-dev
    image: ghcr.io/vortexntnu/vortex-cv:main
    privileged: true  #Give the container access to all your files and all connected devices

    volumes:
      - "../..:/vortex_ws/src"
      - "/dev:/dev"

    stdin_open: true    
    tty: true           
    network_mode: host  
    entrypoint: ["/bin/bash", "-l"]

  cv-local:
    container_name: cv-local
    build: 
      context: ../..
      dockerfile: vortex-cv/docker/Dockerfile.local
      
    # privileged: true  #Give the container access to all your files and all connected devices

    # volumes:
    #  - "../..:/home/vortex/cv_ws/src"
    #  - "/dev:/dev"

    stdin_open: true    
    tty: true           
    network_mode: host  
    environment:
      DISPLAY: :0
    entrypoint: ["/bin/bash", "-l"]



  cv-aruco:
    container_name: cv-aruco
    build: 
      context: ../..
      dockerfile: vortex-cv/docker/Dockerfile.aruco

    volumes:
      - "../../vortex-cv:/vortex_ws/src/vortex-cv"
      - "/dev:/dev"
    stdin_open: true    
    tty: true           
    network_mode: host  
    environment:
      DISPLAY: :0
    entrypoint: ["/bin/bash", "-l"]


  cv-test:
    container_name: cv-test
    build: 
      context: ../..
      dockerfile: vortex-cv/docker/Dockerfile.test
      
    volumes:
        - "../..:/home/vortex/cv_ws/src"
        - "/dev:/dev"
        
    stdin_open: true    
    tty: true           
    network_mode: host  
    environment:
      DISPLAY: :0
    entrypoint: ["/bin/bash", "-l"]