FROM ros:melodic

ARG distro=melodic
ARG DEBIAN_FRONTEND=noninteractive

# Create vortex user
RUN useradd -ms /bin/bash \
    --home /home/vortex  vortex
RUN echo "vortex:vortex" | chpasswd
RUN usermod -aG sudo vortex

#ROS package dependencies
RUN apt update && \
    apt install -y --no-install-recommends \
    python-pip \
    python-catkin-tools \
    libx11-dev 

#ROS packages
RUN apt update && \
    apt install -y --no-install-recommends \
    ros-${distro}-tf \
    ros-${distro}-cv-bridge \
    ros-${distro}-image-transport 



#Python package dependencies
#RUN pip install \
#    numpy \
#    scipy \
#    statistics \
#    turtle \
#    scikit-learn 
    #opencv-python


# Add source to .bashrc file
RUN echo "source /opt/ros/${distro}/setup.bash" >> /home/vortex/.bashrc
RUN echo "source /home/vortex/cv_ws/devel/setup.bash" >> /home/vortex/.bashrc

RUN mkdir -p /home/vortex/cv_ws/src
RUN chown -R vortex /home/vortex/cv_ws


CMD ["/bin/bash"]