FROM ghcr.io/vortexntnu/vortex-cv:main

RUN pip install statistics && \
    pip install scipy && \
    pip install matplotlib && \
    pip install sklearn && \
    pip install scikit-learn && \
    pip install plumbum




RUN sudo apt install -y --no-install-recommends \
    ros-melodic-tf2-geometry-msgs \
    ros-melodic-ros-numpy \
    python-tk 


