<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>perception_setup</name>
  <version>0.0.0</version>
  <description>Launch package for perception</description>
  <maintainer email="jorgen.fjermedal@hotmail.com">jorgen</maintainer>
  <maintainer email="89779148+kluge7@users.noreply.github.com">kluge7</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <exec_depend>ros2launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <!-- <exec_depend>isaac_ros_yolov8</exec_depend>
  <exec_depend>isaac_ros_yolov26_obb</exec_depend>
  <exec_depend>isaac_ros_yolov26_seg</exec_depend>
  <exec_depend>isaac_ros_yolov26_cls</exec_depend>
  <exec_depend>isaac_ros_tensor_rt</exec_depend>
  <exec_depend>isaac_ros_dnn_image_encoder</exec_depend>
  <exec_depend>isaac_ros_image_proc</exec_depend>
  <exec_depend>realsense2_camera</exec_depend>
  <exec_depend>spinnaker_camera_driver</exec_depend> -->
  <exec_depend>valve_detection</exec_depend>
  <exec_depend>valve_subtype_resolver</exec_depend>
  <exec_depend>image_filtering</exec_depend>
  <exec_depend>aruco_detector</exec_depend>
  <exec_depend>gstreamer_from_ros</exec_depend>
  <exec_depend>gstreamer_to_ros</exec_depend>
  <exec_depend>vortex_cv_util_nodes</exec_depend>
  <exec_depend>pipeline_intersection_following</exec_depend>
  <exec_depend>pipeline_end_detector</exec_depend>
  <exec_depend>yolo_segmentation</exec_depend>
  <exec_depend>yolo_object_detection</exec_depend>
  <exec_depend>yolo_classify</exec_depend>
  <exec_depend>pipeline_line_fitting</exec_depend>
  <exec_depend>bearing_direction_server</exec_depend>
  <exec_depend>pipeline_image_endpoints_detector</exec_depend>
  <exec_depend>pipeline_endpoint_position_estimator</exec_depend>
  <exec_depend>pipeline_inspection_fsm</exec_depend>
  <exec_depend>waypoint_manager</exec_depend>
  <exec_depend>landmark_server</exec_depend>
  <exec_depend>irls_line_trigger</exec_depend>
  <exec_depend>docking_camera_yolo_direction_waypoint</exec_depend>
  <exec_depend>docking_position_estimator</exec_depend>
  <exec_depend>subsea_docking_fsm</exec_depend>
  <exec_depend>line_detection_ransac</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
