/**:
  ros__parameters:
    topic:
      image_sub_topic: /fls_publisher/display_mono
      line_segments_pub_topic: line_detection/line_segments
      color_overlay_pub_topic: line_detection/visualization
      canny_debug_pub_topic: line_detection/canny_image
      canny_overlay_pub_topic: line_detection/canny_overlay

    canny:
      low_threshold: 100
      high_threshold: 200
      aperture_size: 3
      L2_gradient: false

    houghp:
      rho: 1.0
      theta: 0.01745329251 # pi / 180
      threshold: 100
      min_line_length: 20.0 # pixels
      max_line_gap: 10.0 # pixels

    mode: "debug" # {"standard", "visualize", "debug"}
