
search_waypoint_1:
  position:
    x: 2.0
    y: 0.0
    z: 0.0
  orientation:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  mode: 0
  convergence_threshold: 0.1

search_waypoint_2:
  position:
    x: 4.0
    y: 0.0
    z: 0.0
  orientation:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  mode: 0
  convergence_threshold: 0.1

search_waypoint_3:
  position:
    x: 4.0
    y: -2.0
    z: 0.0
  orientation:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  mode: 0
  convergence_threshold: 0.1

search_waypoint_4:
  position:
    x: 2.0
    y: -2.0
    z: 0.0
  orientation:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  mode: 0
  convergence_threshold: 0.1
