name: Publish base Docker image to ghcr

on:
  push:
    branches: [ main, cleanup/docker ]
    paths:
      - .github/workflows/**
      - docker/** 
    
  workflow_dispatch:

  pull_request:
    types: [opened, reopened]
    branches: [ main ]
    paths:
    - .github/workflows/**
    - docker/** 

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout own repository
        uses: actions/checkout@v3


      # Upload image to ghcr
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/vortex-cv-base-image

      # Enable image layer caching
      - name: setup buildx 
        uses: docker/setup-buildx-action@v2

      # Build and push image
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ..
          file: ./docker/Dockerfile.base
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max