name: Run automated formatting

on: [pull_request, push]

defaults:
  run:
    shell: bash

env:
  PYTHON_DIR: './'

jobs:
  run-formatting:
    runs-on: ubuntu-18.04
    
    strategy:
      matrix:
        # in this example, there is a newer version already installed, 3.7.7, so the older version will be downloaded
        python-version: ['3.8', '2.7']
    
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install black[python2] flake8 isort

      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Run Python import sorting
        run: python3 -m isort ${{ env.PYTHON_DIR}}

      - name: Run Python black formatting 
        run: python3 -m black ${{ env.PYTHON_DIR}}

      - name: Commit fixed formatting
        uses: Endbug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: 'Fix formatting'

      - name: Run Python flake8 check
        run: python3 -m flake8 ${{ env.PYTHON_DIR}} --max-line-length=120 --select=F,W,E --ignore=W503,E203

