on: push
name: clang-format Code Formatter
jobs:
  lint:
    name: clang-format Code Formatter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with: 
        ref: ${{ github.head_ref }}
    - name: Clang Code Formatter
      uses: ivanludvig/clang-format-action@v1.4
      env:
        GITHUB_TOKEN: ${ { secrets.GITHUB_TOKEN } }